title: esp32gateway
description: ESP32 Gateway
#url: ""

# site urls
# add the url for the domain,
# on gh-pages follow the pattern: https://username.github.io 
url: https://wizard-of-things.github.io/esp32gateway
# add subsection of the domain,
# on gh-pages this is a / followed by the name of the repository
baseurl: /esp32gateway

markdown: kramdown
permalink: /:title
google_analytics: UA-
youtube: https://www.youtube.com/user/
github:
  repository_url: https://github.com/wizard-of-things/esp32gateway
  raw_content_url: https://raw.githubusercontent.com/wizard-of-things/esp32gateway/master
exclude: ["datasheets", "Gemfile", "Gemfile.lock", "contributing.md", "Makefile", "readme.md", "scripts", "firmware"]
include: ["_data"]
